//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluentify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int ChoiceId { get; set; }
        public int QuestionId { get; set; }
        public string ChoiceText { get; set; }
        public int Correct { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
