//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluentify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModuleDetail
    {
        public int UserModuleId { get; set; }
        public int UserId { get; set; }
        public int ModuleId { get; set; }
        public int Score { get; set; }
    
        public virtual User User { get; set; }
        public virtual Module Module { get; set; }
    }
}
